apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-backend-migrations
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-redis
          image: ghcr.io/sikalabs/slu:v0.95.1
          command:
            - "/bin/sh"
            - "-c"
            - "slu wait-for tcp -a {{.Release.Name}}-redis:6379"
      containers:
        - name: migrations
          image: redis
          command: ["/bin/sh", "-c"]
          args: ["sleep 10 && redis-cli -h {{.Release.Name}}-redis incrby counter 10000"]
      restartPolicy: Never
